Add at-try!(x) macro
iamed2/ResultTypes.jl pull request #17
Opened 2020-01-31 04:05 UTC by kmsquire

* Immediately returns an error `x` is an error, otherwise unwraps `x`

This mimics the behavior of the macro of the same name in Rust.  

Rust has actually moved away from this macro, now adding `?` to the end of `Result` types instead.  That option isn't available to Julia (unless, perhaps, Julia moves towards using `ResultTypes` by default.)

I really wanted to call this `@?`, but question marks are not valid identifiers (they're syntax).  I also tried `@/` (a `?` without pressing shift, on US keyboards at least).  But that looked funny, so I went with precedence.

One other Rust-like behavior that this assumes is that exceptions higher in the stack will be converted to different exceptions as the stack unwinds.  This is not common in Julia code (because exceptions are usually thrown, so there's little need to `convert` them).  An additional `Result` `convert` method was added to make this easier, but users will still need to add `convert` methods for converting between their own exception types.

Example from the tests:

```julia
using ResultTypes

struct BarError <: Exception end
struct FooError <: Exception end
Base.convert(::Type{FooError}, ::BarError) = FooError()

function isbar(x)::Result{Bool, BarError}
    x == "foo" && return BarError()
    return x == "bar"
end

function foo(x)::Result{Int, FooError}
    bar = @try!(isbar(x))
    return bar ? 42 : 13
end

foobar = foo("bar") # unwrap(foobar) === 42
foofoo = foo("foo") # unwrap_error(foofoo) === FooError()
football = foo("tball") # unwrap(football) === 13
```

2020-01-31 20:03 UTC, iamed2 commented
Looks good, but here's an additional suggestion:

What about an optional second argument that is a replacement exception to return? This will prevent people from having to necessarily pirate exception conversions in some cases, while still adding the convenience of the compact early return syntax.

2020-02-01 03:42 UTC, kmsquire commented
Okay, @iamed2, I added a version which takes an error as the second argument.  Let me know if you want any changes.

2020-02-01 14:03 UTC, kmsquire commented
I just realized that `!` is the syntax for macro calls in rust (I've only dabbled in the language).  Since we're not modifying our arguments here, I'm going to change this to @try.

2020-02-01 14:12 UTC, kmsquire commented
... which of course doesn't work because `try` is a keyword... (* sigh *)

2020-02-01 16:46 UTC, kmsquire commented
Actually, I just learned that it is possible to define `@try`.  Will push that change again.

2020-02-01 17:24 UTC, kmsquire commented
Ready for re-review.

2020-02-04 18:13 UTC, iamed2 requested changes
Please undo the whitespace changes, otherwise this is good to go and I appreciate it!

2020-02-05 07:51 UTC, kmsquire commented
Sorry, forgot that I was using an autoformatter.  Will fix.

2020-02-05 08:08 UTC, kmsquire commented
Should be good to go!

2020-02-05 16:37 UTC, iamed2 approved these changes

2020-02-05 16:37 UTC, iamed2 commented
Thanks!

2020-02-05 16:38 UTC, merged